### ISSUE TITLE
su: must be run from a terminal

### ISSUE THREAD

**Issue by redgenie** [markoshust/magento-docker#76]
Cron is failing with the following error:
```
su: must be run from a terminal
```

**Comment by mattwkcc** [comment]
@redgenie I was able to get it working by rebuilding after changing 'php/bin/setup-config' to look like this:
```
echo "*/1 * * * * /usr/local/bin/php $SRC_DIR/update/cron.php > /proc/1/fd/2 2>&1" | crontab - \
  && (crontab -l ; echo "*/1 * * * * /usr/local/bin/php $SRC_DIR/bin/magento-php cron:run > /proc/1/fd/2 2>&1") | crontab - \
  && (crontab -l ; echo "*/1 * * * * /usr/local/bin/php $SRC_DIR/bin/magento-php setup:cron:run > /proc/1/fd/2 2>&1") | crontab -
```

Watching compose I started seeing:
 ```php_1  | Ran jobs by schedule.
php_1  | Ran jobs by schedule.```

If your images or css stop working delete pub/static/* and restart compose.

**Comment by redgenie** [comment]
The problem is that this approach will make the cron run as root, which will mess with the permissions

**Comment by redgenie** [comment]
@markoshust any suggestions?

**Comment by markoshust** [comment]
Everything around filesystem permissions was rewritten. The new images have been published, and the cron jobs should be resolved also. There is a new `./bin/fixperms` script which should resolve anything that arises. 

https://github.com/markoshust/magento-docker/blob/master/images/php/7.1/Dockerfile#L41
