### ISSUE TITLE
Error in admin panel

### ISSUE THREAD

**Issue by dannysemi** [markoshust/magento-docker#77]
I get the following error on every page of the admin panel:

"A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

This happens with a clean installation using both the archive and composer methods. I also tried different magento versions with the same result.

**Comment by markoshust** [comment]
The technical perspective for how filesystem ownerships works was completely changed. Please check out the new images. If you continue to experience an issue, please feel free to reopen this ticket. Cheers -Mark
