### ISSUE TITLE
Steps 6-7

### ISSUE THREAD

**Issue by avremel** [markoshust/magento-docker#79]
Step 6: I don't see a etc/hosts file, am I supposed to create one?

Step 7: I am getting the following error, and I can't access my test domain. 

```
chown: changing ownership of '/var/www/.composer/vendor/laravel/installer': Operation not permitted
chown: changing ownership of '/var/www/.composer/vendor/laravel': Operation not permitted
chown: changing ownership of '/var/www/.composer/vendor': Operation not permitted
chown: changing ownership of '/var/www/.composer/.htaccess': Operation not permitted
```
Sudo not helping

**Comment by markoshust** [comment]
Re: step 6, the file is `/etc/hosts`. You should have it on your Mac. I'm not sure where to place it on Windows machines.

Re: step 7, I noticed some permission problems with how the bin scripts were written, and with the location of the `~/.composer` home path in docker-compose-dev.yml. I updated all of the files, please blow away your install and try again:

```
mkdir magento2 && cd $_
git init
git remote add origin git@github.com:markoshust/magento-docker.git
git fetch origin
git checkout origin/master -- compose/magento-2
mv compose/magento-2/* .
rm -rf compose .git
git init
```

Then continue with the rest of the instructions at https://github.com/markoshust/magento-docker#setup-a-new-magento-2-project -- this should resolve any issues you were having. Note that you should probably remove all your local docker volumes and etc. to make sure any old files aren't carried over.
